/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as UploadsImport } from './routes/uploads'
import { Route as LoginImport } from './routes/login_'
import { Route as IndexImport } from './routes/index'
import { Route as UploadsUploadIdImport } from './routes/uploads_.$uploadId'

// Create/Update Routes

const UploadsRoute = UploadsImport.update({
  path: '/uploads',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const UploadsUploadIdRoute = UploadsUploadIdImport.update({
  path: '/uploads/$uploadId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/uploads': {
      id: '/uploads'
      path: '/uploads'
      fullPath: '/uploads'
      preLoaderRoute: typeof UploadsImport
      parentRoute: typeof rootRoute
    }
    '/uploads/$uploadId': {
      id: '/uploads/$uploadId'
      path: '/uploads/$uploadId'
      fullPath: '/uploads/$uploadId'
      preLoaderRoute: typeof UploadsUploadIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  LoginRoute,
  UploadsRoute,
  UploadsUploadIdRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/login",
        "/uploads",
        "/uploads/$uploadId"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/login": {
      "filePath": "login_.tsx"
    },
    "/uploads": {
      "filePath": "uploads.tsx"
    },
    "/uploads/$uploadId": {
      "filePath": "uploads_.$uploadId.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
